Controllers/CartController.cs
using BestStoreMVC.Models;
using BestStoreMVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BestStoreMVC.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly decimal shippingFee;

        public CartController(ApplicationDbContext context, IConfiguration configuration
            , UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
            shippingFee = configuration.GetValue<decimal>("CartSettings:ShippingFee");
        }
        public IActionResult Index()
        {
            List<OrderItem> cartItems = CartHelper.GetCartItems(Request, Response, context);
            decimal subtotal = CartHelper.GetSubtotal(cartItems);

            ViewBag.CartItems = cartItems;
            ViewBag.ShippingFee = shippingFee;
            ViewBag.Subtotal = subtotal;
            ViewBag.Total = subtotal + shippingFee;

            return View();
        }
        [Authorize]
        [HttpPost]
        public IActionResult Index(CheckoutDto model)
        {
            List<OrderItem> cartItems = CartHelper.GetCartItems(Request, Response, context);
            decimal subtotal = CartHelper.GetSubtotal(cartItems);


            ViewBag.CartItems = cartItems;
            ViewBag.ShippingFee = shippingFee;
            ViewBag.Subtotal = subtotal;
            ViewBag.Total = subtotal + shippingFee;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Check if shopping cart is empty or not
            if (cartItems.Count == 0)
            {
                ViewBag.ErrorMessage = "Your cart is empty";
                return View(model);
            }


            TempData["DeliveryAddress"] = model.DeliveryAddress;
            TempData["PaymentMethod"] = model.PaymentMethod;


            if (model.PaymentMethod == "paypal" || model.PaymentMethod == "credit_card")
            {
                return RedirectToAction("Index", "Checkout");
            }

            return RedirectToAction("Confirm");
        }



        public IActionResult Confirm()
        {
            List<OrderItem> cartItems = CartHelper.GetCartItems(Request, Response, context);
            decimal total = CartHelper.GetSubtotal(cartItems) + shippingFee;
            int cartSize = 0;
            foreach (var item in cartItems)
            {
                cartSize += item.Quantity;
            }


            string deliveryAddress = TempData["DeliveryAddress"] as string ?? "";
            string paymentMethod = TempData["PaymentMethod"] as string ?? "";
            TempData.Keep();


            if (cartSize == 0 || deliveryAddress.Length == 0 || paymentMethod.Length == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.DeliveryAddress = deliveryAddress;
            ViewBag.PaymentMethod = paymentMethod;
            ViewBag.Total = total;
            ViewBag.CartSize = cartSize;

            return View();
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Confirm(int any)
        {
            var cartItems = CartHelper.GetCartItems(Request, Response, context);

            string deliveryAddress = TempData["DeliveryAddress"] as string ?? "";
            string paymentMethod = TempData["PaymentMethod"] as string ?? "";
            TempData.Keep();

            if (cartItems.Count == 0 || deliveryAddress.Length == 0 || paymentMethod.Length == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            var appUser = await userManager.GetUserAsync(User);
            if (appUser == null)
            {
                return RedirectToAction("Index", "Home");
            }

            // save the order
            var order = new Order
            {
                ClientId = appUser.Id,
                Items = cartItems,
                ShippingFee = shippingFee,
                DeliveryAddress = deliveryAddress,
                PaymentMethod = paymentMethod,
                PaymentStatus = "pending",
                PaymentDetails = "",
                OrderStatus = "created",
                CreatedAt = DateTime.Now,
            };

            context.Orders.Add(order);
            context.SaveChanges();


            // delete the shopping cart cookie
            Response.Cookies.Delete("shopping_cart");

            ViewBag.SuccessMessage = "Order created successfully";

            return View();
        }

    }
}

Controllers/ClientOrdersController.cs
using BestStoreMVC.Models;
using BestStoreMVC.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BestStoreMVC.Controllers
{
    [Authorize(Roles = "client")]
    [Route("/Client/Orders/{action=Index}/{id?}")]
    public class ClientOrdersController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly int pageSize = 5;

        public ClientOrdersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(int pageIndex)
        {
            var currentUser = await userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("Index", "Home");
            }

            IQueryable<Order> query = context.Orders
                .Include(o => o.Items).OrderByDescending(o => o.Id)
                .Where(o => o.ClientId == currentUser.Id);

            if (pageIndex <= 0)
            {
                pageIndex = 1;
            }


            decimal count = query.Count();
            int totalPages = (int)Math.Ceiling(count / pageSize);

            query = query.Skip((pageIndex - 1) * pageSize).Take(pageSize);


            var orders = query.ToList();

            ViewBag.Orders = orders;
            ViewBag.PageIndex = pageIndex;
            ViewBag.TotalPages = totalPages;

            return View();
        }


        public async Task<IActionResult> Details(int id)
        {
            var currentUser = await userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var order = context.Orders.Include(o => o.Items)
                .ThenInclude(oi => oi.Product)
                .Where(o => o.ClientId == currentUser.Id).FirstOrDefault(o => o.Id == id);


            if (order == null)
            {
                return RedirectToAction("Index");
            }


            return View(order);
        }
    }
}

Views/Cart/Confirm.cshtml
@{
}


<div class="mx-auto rounded border p-4" style="width: 420px">
    <h2 class="text-center mb-3">Order Details</h2>
    <hr />

    @if (ViewBag.SuccessMessage != null)
    {
        <div class="alert alert-success" role="alert">@ViewBag.SuccessMessage</div>
        <a class="btn btn-outline-primary" asp-controller="ClientOrders" asp-action="Index">Back</a>
    }
    else
    {
        <div class="row mb-3">
            <div class="col-5">Delivery Address</div>
            <div class="col-7">@ViewBag.DeliveryAddress</div>
        </div>
        <div class="row mb-3">
            <div class="col-5">Payment Method</div>
            <div class="col-7">@ViewBag.PaymentMethod</div>
        </div>
        <div class="row mb-3">
            <div class="col-5">Total Amount</div>
            <div class="col-7">@(ViewBag.Total)$</div>
        </div>
        <div class="row mb-3">
            <div class="col-5">Quantity</div>
            <div class="col-7">@(ViewBag.CartSize)</div>
        </div>


        <form method="post">
            <div class="row">
                <div class="col-sm-6 d-grid">
                    <button type="submit" class="btn btn-primary">Confirm</button>
                </div>
                <div class="col-sm-6 d-grid">
                    <a class="btn btn-outline-primary" asp-controller="Cart" asp-action="Index">Back</a>
                </div>
            </div>
        </form>
    }

</div>

Views/Cart/Index.cshtml
@model CheckoutDto
@{
}


<div class="row border rounded-3">
    <div class="col-md-8 p-3">
        <h4>Shopping Cart</h4>
        <hr />


        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-warning alert-dismissible fade show mt-4" role="alert">
                <strong>@ViewBag.ErrorMessage</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        <table class="table align-middle">
            <tbody>
                @foreach (var item in ViewBag.CartItems)
                {
                    <tr>
                        <td>
                            <img src="/products/@item.Product.ImageFileName" width="100" class="rounded" alt="...">
                        </td>
                        <td>
                            <h4>@item.Product.Name</h4>
                            <p>
                                Brand: @item.Product.Brand<br>
                                Category: @item.Product.Category<br>
                                Price: @(item.Product.Price)$
                            </p>
                        </td>
                        <td style="white-space:nowrap">
                            <button type="button" class="btn btn-outline-secondary btn-sm"
                                    onclick="decrease(@item.Product.Id)">
                                -
                            </button>
                            <span class="border rounded-3 p-2 m-1">@item.Quantity</span>
                            <button type="button" class="btn btn-outline-secondary btn-sm"
                                    onclick="increase(@item.Product.Id)">
                                +
                            </button>
                        </td>
                        <td>@(item.UnitPrice * item.Quantity)$</td>
                        <td>
                            <i class="bi bi-trash text-danger h4" style="cursor: pointer" onclick="remove(@item.Product.Id)"></i>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-4">
        <div class="text-white rounded my-2 p-3" style="background-color: #08618d;">
            <h4>Order Summary</h4>
            <hr />


            @using Microsoft.AspNetCore.Identity
            @inject SignInManager<ApplicationUser> SignInManager


            @if (!SignInManager.IsSignedIn(User))
            {
                <div class="row">
                    <div class="col">
                        <p>Subtotal:</p>
                    </div>
                    <div class="col">
                        <p class="text-end">@(ViewBag.Subtotal)$</p>
                    </div>
                </div>


                <div class="row">
                    <div class="col d-grid">
                        <a class="btn btn-light" asp-controller="Account" asp-action="Register">Register</a>
                    </div>
                    <div class="col d-grid">
                        <a class="btn btn-outline-light" asp-controller="Account" asp-action="Login">Login</a>
                    </div>
                </div>
            }
            else
            {
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label">Delivery Address</label>
                        <input type="text" class="form-control" asp-for="DeliveryAddress">
                        <span asp-validation-for="DeliveryAddress" class="text-warning"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Payment Method</label>
                        <select class="form-select" asp-for="PaymentMethod">
                            <option value="cash">Cash on Delivery</option>
                            <option value="credit_card">Credit Card</option>
                            <option value="paypal">Paypal</option>
                        </select>
                    </div>

                    <hr>


                    <div class="row">
                        <div class="col">
                            <p>Subtotal:</p>
                        </div>
                        <div class="col">
                            <p class="text-end">@(ViewBag.Subtotal)$</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <p>Shipping:</p>
                        </div>
                        <div class="col">
                            <p class="text-end">@(ViewBag.ShippingFee)$</p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <p>Total:</p>
                        </div>
                        <div class="col">
                            <p class="text-end">@(ViewBag.Total)$</p>
                        </div>
                    </div>


                    <div class="d-grid">
                        <button class="btn btn-outline-light" type="submit">Checkout</button>
                    </div>
                </form>
            }
        </div>
    </div>
</div>